"""supprime table eleve, copie.eleve_id devient identifiant_hakili

Revision ID: 25898695d3c4
Revises: 3eee6db8ae6e
Create Date: 2026-07-17 01:52:14.126737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25898695d3c4'
down_revision: Union[str, Sequence[str], None] = '3eee6db8ae6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Base vidée avant cette migration (données de test, aucune donnée à
    préserver) — voir procédure dans le message de commit / rapport de
    chantier : `alembic downgrade base` puis `alembic upgrade head`.
    L'ordre ci-dessous est important : il faut retirer la contrainte de clé
    étrangère copie -> eleve avant de pouvoir supprimer la table eleve.
    """
    # ### commands auto generated by Alembic - adjusted pour l'ordre des opérations ###
    op.add_column('copie', sa.Column('identifiant_hakili', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('copie_eleve_id_fkey'), 'copie', type_='foreignkey')
    op.drop_column('copie', 'eleve_id')
    op.drop_table('eleve')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    Ordre important, symétrique de upgrade() : la table eleve doit exister
    avant de pouvoir y créer une clé étrangère depuis copie.
    """
    # ### commands auto generated by Alembic - adjusted pour l'ordre des opérations ###
    op.create_table('eleve',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('identifiant_hakili', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_naissance', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('centre_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centre.id'], name=op.f('eleve_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('eleve_pkey')),
    sa.UniqueConstraint('identifiant_hakili', name=op.f('eleve_identifiant_hakili_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.add_column('copie', sa.Column('eleve_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('copie_eleve_id_fkey'), 'copie', 'eleve', ['eleve_id'], ['id'])
    op.drop_column('copie', 'identifiant_hakili')
    # ### end Alembic commands ###
