"""init schema

Revision ID: 3eee6db8ae6e
Revises: 
Create Date: 2026-07-09 17:07:56.294623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3eee6db8ae6e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('centre',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eleve',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identifiant_hakili', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=255), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('centre_id', sa.UUID(), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifiant_hakili')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'responsable_centre', 'enseignant', name='userrole'), nullable=False),
    sa.Column('centre_id', sa.UUID(), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('copie',
    sa.Column('copy_id', sa.String(length=255), nullable=False),
    sa.Column('eleve_id', sa.UUID(), nullable=False),
    sa.Column('classe', sa.String(length=50), nullable=False),
    sa.Column('annee_scolaire', sa.String(length=50), nullable=False),
    sa.Column('date_soumission', sa.Date(), nullable=False),
    sa.Column('notes_finales', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['eleve_id'], ['eleve.id'], ),
    sa.PrimaryKeyConstraint('copy_id')
    )
    op.create_table('document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('copy_id', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('fichier', postgresql.BYTEA(), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['copy_id'], ['copie.copy_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    op.drop_table('copie')
    op.drop_table('utilisateur')
    op.drop_table('eleve')
    op.drop_table('centre')
    # ### end Alembic commands ###
    # Ajouté à la main : drop_table('utilisateur') ne supprime pas le type ENUM
    # Postgres associé à la colonne role (userrole) — sans ce nettoyage,
    # "alembic downgrade base" puis "alembic upgrade head" échoue sur
    # "type userrole already exists" au moment de recréer la table utilisateur.
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)
