"""nouveau login Sheets : credentials remplace utilisateur, centre supprimee

Revision ID: d919411e7423
Revises: 25898695d3c4
Create Date: 2026-07-17 16:33:36.554401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd919411e7423'
down_revision: Union[str, Sequence[str], None] = '25898695d3c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Ordre important : utilisateur porte une FK vers centre (centre_id), donc
    utilisateur doit être supprimée avant centre. drop_table('utilisateur')
    ne supprime pas le type ENUM Postgres associé à sa colonne role
    (userrole) — même piège que la migration précédente (25898695d3c4) sur
    l'enum d'un autre modèle : on le supprime explicitement pour ne pas
    laisser un type orphelin qui ferait échouer un futur downgrade+upgrade.
    """
    # ### commands auto generated by Alembic - adjusted pour l'ordre des opérations ###
    op.create_table('credentials',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.drop_table('utilisateur')
    op.drop_table('centre')
    # ### end Alembic commands ###
    sa.Enum(name='userrole').drop(op.get_bind(), checkfirst=True)


def downgrade() -> None:
    """Downgrade schema.

    Ordre important, symétrique de upgrade() : centre doit exister avant de
    recréer utilisateur (sa FK centre_id la référence).
    """
    # ### commands auto generated by Alembic - adjusted pour l'ordre des opérations ###
    op.create_table('centre',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('centre_pkey'))
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('nom', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('admin', 'responsable_centre', 'enseignant', name='userrole'), autoincrement=False, nullable=False),
    sa.Column('centre_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('classe', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['centre_id'], ['centre.id'], name=op.f('utilisateur_centre_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('utilisateur_pkey')),
    sa.UniqueConstraint('email', name=op.f('utilisateur_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('credentials')
    # ### end Alembic commands ###
