"""supprime table credentials, connexion nom+PIN

Revision ID: f8928cd01df9
Revises: d919411e7423
Create Date: 2026-07-20 16:02:16.830761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8928cd01df9'
down_revision: Union[str, Sequence[str], None] = 'd919411e7423'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Connexion refondue en nom+PIN (voir chantier connexion nom+PIN) : le PIN
    vit en clair dans le Sheet personnel, plus de mot de passe stocké côté
    PostgreSQL — la table credentials n'a plus d'utilité.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credentials',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date_creation', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('email', name=op.f('credentials_pkey'))
    )
    # ### end Alembic commands ###
